-- Migration: Drop and recreate Accounts tables for single-company mode
-- WARNING: Do not run without a backup. This file drops and recreates tables.

BEGIN;

-- Drop existing Accounts-related tables if they exist
DROP TABLE IF EXISTS public.journal_lines;
DROP TABLE IF EXISTS public.ledger_entries;
DROP TABLE IF EXISTS public.customer_payments;
DROP TABLE IF EXISTS public.vendor_payments;
DROP TABLE IF EXISTS public.budget_lines;
DROP TABLE IF EXISTS public.invoices;
DROP TABLE IF EXISTS public.bills;
DROP TABLE IF EXISTS public.expenses;
DROP TABLE IF EXISTS public.income;
DROP TABLE IF EXISTS public.budgets;
DROP TABLE IF EXISTS public.chart_of_accounts;
DROP TABLE IF EXISTS public.journal_entries;
DROP TABLE IF EXISTS public.customers;
DROP TABLE IF EXISTS public.vendors;
DROP TABLE IF EXISTS public.event_store;

-- Create chart_of_accounts
CREATE TABLE public.chart_of_accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code varchar(50) NOT NULL,
  account_name varchar(255) NOT NULL,
  account_type varchar(50) NOT NULL,
  parent_account_id integer NULL,
  is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_parent ON public.chart_of_accounts(parent_account_id);

-- Create journal_entries
CREATE TABLE public.journal_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference varchar(255),
  description varchar(1024),
  status varchar(50) NOT NULL DEFAULT 'draft',
  date timestamptz NOT NULL DEFAULT now(),
  submitted_at timestamptz NULL,
  approved_at timestamptz NULL,
  posted_at timestamptz NULL
);

-- Create journal_lines
CREATE TABLE public.journal_lines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id integer NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  account_id integer NOT NULL REFERENCES public.chart_of_accounts(id),
  memo varchar(255) NULL,
  debit numeric(14,2) NOT NULL DEFAULT 0,
  credit numeric(14,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_journal_lines_journal ON public.journal_lines(journal_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON public.journal_lines(account_id);

-- Create ledger_entries
CREATE TABLE public.ledger_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id integer NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  account_id integer NOT NULL REFERENCES public.chart_of_accounts(id),
  debit numeric(14,2) NOT NULL DEFAULT 0,
  credit numeric(14,2) NOT NULL DEFAULT 0,
  posting_date timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_journal ON public.ledger_entries(journal_id);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_account ON public.ledger_entries(account_id);

-- Budgets and lines
CREATE TABLE public.budgets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  fiscal_year integer NOT NULL,
  total_amount numeric(14,2) NOT NULL,
  status varchar(50) NOT NULL DEFAULT 'draft',
  start_date timestamptz NOT NULL,
  end_date timestamptz NOT NULL
);

CREATE TABLE public.budget_lines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id integer NOT NULL REFERENCES public.budgets(id) ON DELETE CASCADE,
  account_id integer NOT NULL REFERENCES public.chart_of_accounts(id),
  allocated_amount numeric(14,2) NOT NULL,
  spent_amount numeric(14,2) NOT NULL DEFAULT 0,
  consumed_percentage numeric(5,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_budget_lines_budget ON public.budget_lines(budget_id);

-- Vendors, bills, vendor payments
CREATE TABLE public.vendors (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255),
  phone varchar(20),
  address varchar(512),
  is_active varchar(50) NOT NULL DEFAULT 'active'
);

CREATE TABLE public.bills (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id integer NOT NULL REFERENCES public.vendors(id),
  bill_number varchar(255) NOT NULL,
  bill_date timestamptz NOT NULL DEFAULT now(),
  due_date timestamptz NULL,
  amount numeric(14,2) NOT NULL,
  paid_amount numeric(14,2) NOT NULL DEFAULT 0,
  status varchar(50) NOT NULL DEFAULT 'draft',
  description varchar(1024),
  journal_id integer NULL REFERENCES public.journal_entries(id)
);
CREATE INDEX IF NOT EXISTS idx_bills_vendor ON public.bills(vendor_id);
CREATE INDEX IF NOT EXISTS idx_bills_number ON public.bills(bill_number);

CREATE TABLE public.vendor_payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id integer NOT NULL REFERENCES public.bills(id) ON DELETE CASCADE,
  payment_date timestamptz NOT NULL DEFAULT now(),
  amount numeric(14,2) NOT NULL,
  reference varchar(255),
  journal_id integer NULL REFERENCES public.journal_entries(id)
);
CREATE INDEX IF NOT EXISTS idx_vendor_payments_bill ON public.vendor_payments(bill_id);

-- Customers, invoices, customer payments
CREATE TABLE public.customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255),
  phone varchar(20),
  address varchar(512),
  is_active varchar(50) NOT NULL DEFAULT 'active'
);

CREATE TABLE public.invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES public.customers(id),
  invoice_number varchar(255) NOT NULL,
  invoice_date timestamptz NOT NULL DEFAULT now(),
  due_date timestamptz NULL,
  amount numeric(14,2) NOT NULL,
  paid_amount numeric(14,2) NOT NULL DEFAULT 0,
  status varchar(50) NOT NULL DEFAULT 'draft',
  description varchar(1024),
  journal_id integer NULL REFERENCES public.journal_entries(id)
);
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON public.invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_number ON public.invoices(invoice_number);

CREATE TABLE public.customer_payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  payment_date timestamptz NOT NULL DEFAULT now(),
  amount numeric(14,2) NOT NULL,
  reference varchar(255),
  journal_id integer NULL REFERENCES public.journal_entries(id)
);
CREATE INDEX IF NOT EXISTS idx_customer_payments_invoice ON public.customer_payments(invoice_id);

-- Expenses and Income
CREATE TABLE public.expenses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(255) NOT NULL,
  amount numeric(14,2) NOT NULL,
  expense_date timestamptz NOT NULL DEFAULT now(),
  account_id integer NOT NULL REFERENCES public.chart_of_accounts(id),
  reference varchar(255),
  journal_id integer NULL REFERENCES public.journal_entries(id),
  status varchar(50) NOT NULL DEFAULT 'draft'
);
CREATE INDEX IF NOT EXISTS idx_expenses_account ON public.expenses(account_id);

CREATE TABLE public.income (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(255) NOT NULL,
  amount numeric(14,2) NOT NULL,
  income_date timestamptz NOT NULL DEFAULT now(),
  account_id integer NOT NULL REFERENCES public.chart_of_accounts(id),
  reference varchar(255),
  journal_id integer NULL REFERENCES public.journal_entries(id),
  status varchar(50) NOT NULL DEFAULT 'draft'
);
CREATE INDEX IF NOT EXISTS idx_income_account ON public.income(account_id);

-- Event store (single-company)
CREATE TABLE public.event_store (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(255) NOT NULL,
  payload json NOT NULL,
  processed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_event_store_type ON public.event_store(event_type);

COMMIT;

-- End of migration
